### ISSUE TITLE
No pod file in the repo

### ISSUE THREAD

**Issue by lmaix** [ksemianov/SwiftyEigen#1]
Hey ! Thanks for this repo. I wanted to try it but I don't see any pod file in the folder Example.

`To run the example project, clone the repo, and run pod install from the Example directory first.`

**Comment by ksemianov** [comment]
Hi! This repo was prepared specifically for this blog post [medium.com/p/fb5cd606220f](https://medium.com/p/fb5cd606220f) Initially, I wanted to publish an example with CococaPods, but ended up doing Swift Package Manager instead. So this line in README should be removed. You do not need to run `pod install`.

**Comment by lmaix** [comment]
Thanks. I don't understand if I can test it or was just for educational purpose?

I mean on a test project I tried to add a Swift Package Manager with this url https://github.com/ksemianov/SwiftyEigen but there is not release number so I can not

**Comment by ksemianov** [comment]
It is intended for educational purposes. Currently, it maps a subset of `Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic>` functionality as an Objective-C class `EIGMatrix`. For your convenience, I've added tag 0.1.0 to the latest commit, so you can add this repository as a package dependency.

As a side note, for small fixed sized matrix manipulations you most likely need `simd` library which is in Apple's SDK [developer.apple.com/documentation/accelerate/working_with_matrices](https://developer.apple.com/documentation/accelerate/working_with_matrices). For arbitrary sized matrices, you might like [github.com/Jounce/Surge](https://github.com/Jounce/Surge)

**Comment by lmaix** [comment]
Thank you I succeed do to what I wanted :)
