### ISSUE TITLE
Submodule missing... what was in CPP/ ?

### ISSUE THREAD

**Issue by SoylentGraham** [ksemianov/SwiftyEigen#2]
I've been scouring tutorials on how to get a C++ lib (.a .framework .dylib, anything! :) into a swift package.

This one was getting close (seemed quite minimal), but the `cpp/` submodule's repos has gone.

It's not clear what was in there, was it just c++ source, or was there a prebuilt lib?

**Comment by SoylentGraham** [comment]
Ah, opening the example xcodeproj shows it's all c++ code.

What made all that source compile? 
`package.swift` has no build instructions for .m/obj-c, nor c++..

Does the swift.package attempt to just build anything in `Sources/` ?

**Comment by ksemianov** [comment]
Hi! Did you take a look at the build instructions in the README? The `CPP` folder is a git submodule that needs to be inited with `git submodule update --init`. Also in the README, there is a link to [an article](https://medium.com/p/fb5cd606220f) explaining the code.

**Comment by SoylentGraham** [comment]
I think you misunderstood

https://github.com/ksemianov/SwiftyEigen/blob/master/Sources/CPP

no longer exists. 

The submodule cannot be initialised

**Comment by ksemianov** [comment]
Did you run `git submodule update --init` after cloning the repo to your local machine and the `Sources/CPP` folder is still empty? What error does your command line show?

**Comment by SoylentGraham** [comment]
Click the link above, it's 404.
The repository url no longer exists.
No amount of running git commands will make the url appear :)

But it's a moot point, I got the information (see 2nd post)

**Comment by ksemianov** [comment]
GitHub is not smart enough to correctly display a git submodule that's pointing to a [GitLab repo](https://gitlab.com/libeigen/eigen/-/tree/0fd6b4f71dd85b2009ee4d1aeb296e2c11fc9d68). Please refer to [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and [Swift Package Manager](https://developer.apple.com/documentation/xcode/creating-a-standalone-swift-package-with-xcode) documentations for your questions.
